### ISSUE TITLE
a quick question about the code

### ISSUE THREAD

**Issue by sysuxyt** [OpenDriveLab/Vista#15]
Thanks for the amazing open-source work! I have a quick question about the code: why is add_lora set to false in the network config when inference but true in training_stage2? It seems to affect the inclusion of trained LORA weights. 
I'm curious about this  difference in configuration. Could you please clarify the rationale behind it. Appreciate your help!

**Comment by Little-Podi** [comment]
That is a feature of LoRA. The trained LoRA weights can be merged into the original weights after training (see [our code](https://github.com/OpenDriveLab/Vista/blob/main/bin_to_st.py#L10-L31)). Therefore, during inference, there is no need to instantiate LoRA layers. In the 2nd training stage, we always keep the LoRA layers to ensure the pretrained weights in the 1st stage are intact. That's why the configurations are set like you said.

**Comment by sysuxyt** [comment]
Ah, got it. Great thanks!

**Comment by Little-Podi** [comment]
No problem :)
