### ISSUE TITLE
Have you considered putting it in carla for closed-loop testing?

### ISSUE THREAD

**Issue by hunkyu** [OpenDriveLab/Vista#19]
Have you considered putting it in carla for closed-loop testing?

**Comment by Little-Podi** [comment]
Hi, thanks for this good question. We haven't tried this yet for two reasons. First, our model is targeting at real-world scenarios, while CARLA is a simulated world with different appearances and rules. Second, although I'm not an expert of CARLA, I think that CARLA itself is a perfect world model of its own scenes. In other words, mimicing a visual world model upon CARLA might be repetitive and meaningless as CARLA already provides the desired functions, i.e. getting the future status.

**Comment by hunkyu** [comment]
@Little-Podi I agree. If we can see the generalization effect in Carla, it is a very good work. If we assume that the world model is good enough, is it possible to achieve SOTA level in the closed-loop performance of Carla?

**Comment by YTEP-ZHI** [comment]
Hi @hunkyu, thank you for your interest and suggestion. We did not conduct the closed-loop experiment ourselves, and it is not planned in the near future due to our current schedule. However, some other studies have conducted these experiments with encouraging results: https://arxiv.org/abs/2411.10171.
